DATA:
    IMAGE_SIZE: 448
    CROP_PCT: 1.0
    
MODEL:
    TYPE: cait
    NAME: cait_m48_448
    PATCH_SIZE: 16
    EMBED_DIM: 768
    DEPTH: 48
    NUM_HEADS: 16
    MLP_RATIO: 4.0
    QKV_BIAS: True
    INIT_VALUES: 1e-6
    DEPTH_TOKEN_ONLY: 2
    DROPPATH: 0.4
