DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: levit
    NAME: levie_256
    DROPPATH: 0.1
    EMBED_DIM: [256, 384, 512]
    NUM_HEADS: [4, 6, 8]
    DEPTH: [4, 4, 4]
    KEY_DIM: 32
    USE_CONV: False
TRAIN:
    LINEAR_SCALED_LR: 1024
    MODEL_EMA: True
    MODEL_EMA_FORCE_CPU: True
