DATA:
    IMAGE_SIZE: 384
    CROP_PCT: 1.0
MODEL:
    TYPE: RepLKNet
    NAME: replknet_31l_384
    NUM_CLASSES: 1000  # 21841 for imagenet 22k
    DROPPATH: 0.3
    LARGE_KERNEL_SIZES: [31, 29, 27, 13]
    LAYERS: [2, 2, 18, 2]
    CHANNELS: [192, 384, 768, 1536]
    DW_RATIO: 1.0
    FFN_RATIO: 4.0
    SMALL_KERNEL: 5
    SMALL_KERNEL_MERGED: False
    NORM_INTER_FEATURES: False
    OUT_INDICES: None 

TRAIN:
    NUM_EPOCHS: 30
    WARMUP_EPOCHS: 1
    BASE_LR: 4e-4
    WARMUP_START_LR: 1e-6
    END_LR: 3e-4
    WEIGHT_DECAY: 1e-8
    LINEAR_SCALED_LR: 256
    MODEL_EMA: True
    ACCUM_ITER: 4
    CUTMIX_ALPHA: 0.0
    MIXUP_ALPHA: 0.0
