DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.9
MODEL:
    TYPE: swin
    NAME: swin_base_patch4_window7_224
    DROPPATH: 0.5
    EMBED_DIM: 128
    STAGE_DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 7
    PATCH_SIZE: 4
