DATA:
    IMAGE_SIZE: 384
    CROP_PCT: 1.0
MODEL:
    TYPE: xcit
    NAME: xcit_small_24_p8_384
    PATCH_SIZE: 8
    EMBED_DIM: 384
    DEPTH: 24
    NUM_HEADS: 8
    ETA: 1e-5
    TOKENS_NORM: True
