DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: shuffle
    NAME: shuffle_vit_tiny_patch4_window7_224
    DROPPATH: 0.1
    EMBED_DIM: 96
    STAGE_DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
