DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: shuffle
    NAME: shuffle_vit_tiny_patch4_window7_224
    DROPPATH: 0.5
    EMBED_DIM: 128
    STAGE_DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 7
