DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: deit
    NAME: deit_base_patch16_224
    PATCH_SIZE: 16
    MLP_RATIO: 4.0
    QKV_BIAS: true
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    DROPOUT: 0.0  # same as paper
    ATTENTION_DROPOUT: 0.1  # same as paper
TRAIN:
    NUM_EPOCHS: 300  # same as paper
    WARMUP_EPOCHS: 5  # same as paper 
    WEIGHT_DECAY: 0.05  # same as paper
    BASE_LR: 5e-4
    WARMUP_START_LR: 1e-6
    END_LR: 0.0
    ACCUM_ITER: 1
    LINEAR_SCALED_LR: 512
    OPTIMIZER:
        NAME: 'AdamW'
        BETAS: (0.9, 0.999)
    DISTILLATION_TYPE: 'hard' 

VALIDATE_FREQ: 1
SAVE_FREQ: 1
REPORT_FREQ: 20

