DATA:
    IMAGE_SIZE: 384
    CROP_PCT: 1.0
MODEL:
    TYPE: deit
    NAME: deit_base_patch16_384
    PATCH_SIZE: 16
    MLP_RATIO: 4.0
    QKV_BIAS: true
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    DROPOUT: 0.0  # same as paper
    ATTENTION_DROPOUT: 0.1  # same as paper
TRAIN: # finetune params
    NUM_EPOCHS: 30
    WARMUP_EPOCHS: 5
    WEIGHT_DECAY: 1e-8
    BASE_LR: 5e-6
    WARMUP_START_LR: 1e-6
    END_LR: 5e-6
    ACCUM_ITER: 1
    LINEAR_SCALED_LR: 512
    OPTIMIZER:
        NAME: 'AdamW'
        BETAS: (0.9, 0.999)
    DISTILLATION_TYPE: 'hard'

VALIDATE_FREQ: 1
SAVE_FREQ: 1
REPORT_FREQ: 20

