DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
    BATCH_SIZE: 128  # effective batch size = 4096
MODEL:
    TYPE: convnext
    NAME: convnext_base
    DEPTHS: [3, 3, 27, 3]
    DIMS: [128, 256, 512, 1024]
    DROPPATH: 0.5
TRAIN:
    ACCUM_ITER: 4  # for single node 8 gpus
