DATA:
    IMAGE_SIZE: 256
    CROP_PCT: 0.875
MODEL:
    TYPE: RepMLP
    NAME: repmlp_b_256
    CHANNELS: [96, 192, 384, 768]
    HEIGHTS: [64, 32, 16, 8]
    WIDTHS: [64, 32, 16, 8]
    NUM_BLOCKS: [2, 2, 12, 2]
    REPARAM_CONV_K: [1, 3]
    SHARESETS_NUMS: [1, 4, 32, 128]
    DEPLOY: False

