DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
    BATCH_SIZE: 256
MODEL:
    TYPE: ResT_V2
    NAME: restv2_tiny
    EMBED_DIMS: [128, 256, 512, 1024]
    NUM_HEADS: [2, 4, 8, 16]
    MLP_RATIOS: [4, 4, 4, 4]
    QKV_BIAS: True
    DEPTHS: [2, 3, 16, 2]
    SR_RATIOS: [8, 4, 2, 1]
    DROPPATH: 0.1
TRAIN:
    ACCUM_ITER: 1
