DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
    BATCH_SIZE: 256
MODEL:
    TYPE: ResT
    NAME: rest_lite
    EMBED_DIMS: [64, 128, 256, 512]
    NUM_HEADS: [1, 2, 4, 8]
    MLP_RATIOS: [4, 4, 4, 4]
    QKV_BIAS: True
    DEPTHS: [2, 2, 2, 2]
    SR_RATIOS: [8, 4, 2, 1]
    APPLY_TRANSFORM: True
    DROPPATH: 0.1
TRAIN:
    ACCUM_ITER: 1
