DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
    BATCH_SIZE: 256
MODEL:
    TYPE: ResT_V2
    NAME: restv2_small
    EMBED_DIMS: [96, 192, 384, 768]
    NUM_HEADS: [1, 2, 4, 8]
    MLP_RATIOS: [4, 4, 4, 4]
    QKV_BIAS: True
    DEPTHS: [1, 2, 12, 2]
    SR_RATIOS: [8, 4, 2, 1]
    DROPPATH: 0.1
TRAIN:
    ACCUM_ITER: 1
