DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: TopFormer
    NAME: topformer_small
    DROPPATH: 0.1
    CHANNELS: [24, 48, 96, 128]
    OUT_CHANNELS: [None, 192, 192, 192]
    EMBED_OUT_INDICE: [2, 4, 6, 9]
    DECODE_OUT_INDICES: [1, 2, 3]
    NUM_HEADS: 6
    C2T_STRIDE: 1
    DEPTH: 4
    CFGS: [[3,   1,  16, 1], # 1/2        0.464K  17.461M
           [3,   4,  24, 2], # 1/4 1      3.44K   64.878M
           [3,   3,  24, 1], #            4.44K   41.772M
           [5,   3,  48, 2], # 1/8 3      6.776K  29.146M
           [5,   3,  48, 1], #            13.16K  30.952M
           [3,   3,  96, 2], # 1/16 5     16.12K  18.369M
           [3,   3,  96, 1], #            41.68K  24.508M
           [5,   6,  128, 2], # 1/32 7     0.129M  36.385M
           [5,   6,  128, 1], #            0.335M  49.298M
           [3,   6,  128, 1], #            0.335M  49.298M
    ]

TRAIN:
    NUM_EPOCHS: 300
    WARMUP_EPOCHS: 30
    BASE_LR: 0.002
    WARMUP_START_LR: 0.0002
    END_LR: 0.0002
    WEIGHT_DECAY: 0.01
    MIXUP_PROB: 0.0
    CUTMIX_ALPHA: 0.0
    LINEAR_SCALED_LR: 1024
    MODEL_EMA: True
    MODEL_EMA_FORCE_CPU: True
