DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.9
    BATCH_SIZE: 256  # effective batch size = 2048
MODEL:
    TYPE: coat_lite
    NAME: coat_lite_mini
    PATCH_SIZE: 4
    EMBED_DIMS: [64, 128, 320, 512]
    SERIAL_DEPTHS: [2, 2, 2, 2]
    PARALLEL_DEPTH: 0
    NUM_HEADS: 8
    MLP_RATIOS: [8, 8, 4, 4]
    DROPPATH: 0.0
TRAIN:
    ACCUM_ITER: 1  # for single node 8 gpus
